---
name: portcullis
version: 0.1.0.0
github: "git@github.com:jzwood/portcullis.git"
license: BSD3
author: "Jake Wood"
maintainer: "Jake Wood"
copyright: "2021 Jake Wood"

extra-source-files:
  - README.md
  - ChangeLog.md
  - src/CodeGen/Html/head.html
  - src/CodeGen/Js/core.js
  - src/CodeGen/Lua/core.lua
  - src/CodeGen/Py/core.py
  - src/CodeGen/Erl/core.erl

data-files:
  - src/CodeGen/Html/head.html
  - src/CodeGen/Js/core.js
  - src/CodeGen/Lua/core.lua
  - src/CodeGen/Py/core.py
  - src/CodeGen/Erl/core.erl

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: A minimalist, functional, dataflow programming language

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.6.5.1
  - directory >= 1.3.6.0
  - filepath == 1.4.2.2
  - hspec == 2.10.10
  - file-embed == 0.0.15.0
  - utf8-string == 1.0.2
  - QuickCheck == 2.14.3

library:
  source-dirs: src

executables:
  portcullis-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - portcullis

tests:
  portcullis-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - portcullis
  doctests:
    source-dirs: doctests
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - doctest
